const icons={computador:'💻',notebook:'💼',switch:'🔌',roteador:'🌐',servidor:'🗄️',impressora:'🖨️','access-point':'📶'};
const typeNames={computador:'PC',notebook:'Notebook',switch:'Switch',roteador:'Roteador',servidor:'Servidor',impressora:'Impressora','access-point':'Access Point'};
let project=emptyProject();let editingId=null;let connectMode=false;let firstConnect=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function emptyProject(){return{version:1,company:{name:'Minha Empresa',group:'',members:'',description:''},departments:[],equipment:[],connections:[],history:[]}}
function id(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(16).slice(2)}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function statusText(s){return s==='manutencao'?'Em manutenção':s==='inativo'?'Inativo':'Ativo'}
function addHistory(type,description){project.history.unshift({id:id('hist'),date:today(),type,description})}

document.addEventListener('DOMContentLoaded',()=>{setupNav();setupCompany();setupDepartments();setupMap();setupHistory();setupSaveOpen();$('#historicoData').value=today();renderAll()});

function setupNav(){ $$('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-btn').forEach(b=>b.classList.remove('active'));$$('.screen').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.target).classList.add('active');if(btn.dataset.target==='mapa')setTimeout(drawConnections,50)})) }
function setupCompany(){ $('#btnSalvarEmpresa').addEventListener('click',()=>{project.company.name=$('#empresaNome').value.trim()||'Minha Empresa';project.company.group=$('#empresaGrupo').value.trim();project.company.members=$('#empresaIntegrantes').value.trim();project.company.description=$('#empresaDescricao').value.trim();addHistory('Configuração','Dados da empresa foram atualizados.');renderAll();alert('Dados da empresa salvos.')}) }
function setupDepartments(){ $('#btnAdicionarDepartamento').addEventListener('click',()=>{const name=$('#novoDepartamento').value.trim();if(!name)return alert('Digite o nome do departamento.');if(project.departments.some(d=>d.name.toLowerCase()===name.toLowerCase()))return alert('Esse departamento já existe.');project.departments.push({id:id('dep'),name});$('#novoDepartamento').value='';addHistory('Configuração',`Departamento "${name}" foi criado.`);renderAll()}) }
function deleteDepartment(depId){const dep=project.departments.find(d=>d.id===depId);if(!dep)return;if(project.equipment.some(e=>e.departmentId===depId))return alert('Esse departamento ainda possui equipamentos. Mova-os antes de excluir.');if(!confirm(`Excluir o departamento "${dep.name}"?`))return;project.departments=project.departments.filter(d=>d.id!==depId);addHistory('Correção',`Departamento "${dep.name}" foi removido.`);renderAll()}

function setupMap(){ $('#btnAdicionarEquipamento').addEventListener('click',addEquipment);$('#btnConectar').addEventListener('click',startConnect);$('#btnCancelarConexao').addEventListener('click',cancelConnect);$('#btnFecharModal').addEventListener('click',closeModal);$('#btnSalvarEquipamento').addEventListener('click',saveEquipmentEdit);$('#btnExcluirEquipamento').addEventListener('click',deleteCurrentEquipment);window.addEventListener('resize',drawConnections) }
function addEquipment(){const type=$('#tipoEquipamento').value;const n=project.equipment.filter(e=>e.type===type).length+1;const e={id:id('eq'),type,name:`${typeNames[type]}-${String(n).padStart(2,'0')}`,departmentId:'',ip:'',prefix:'',mac:'',status:'ativo',notes:'',x:40+(project.equipment.length%5)*135,y:50+Math.floor(project.equipment.length/5)*115};project.equipment.push(e);addHistory('Expansão',`${e.name} foi adicionado ao mapa.`);renderAll()}
function renderMap(){const canvas=$('#networkCanvas');canvas.querySelectorAll('.equipment').forEach(el=>el.remove());$('#emptyNetwork').classList.toggle('hidden',project.equipment.length>0);project.equipment.forEach(e=>{const el=document.createElement('div');el.className='equipment';el.dataset.id=e.id;el.style.left=e.x+'px';el.style.top=e.y+'px';const dep=project.departments.find(d=>d.id===e.departmentId);el.innerHTML=`<span class="icon">${icons[e.type]||'🔧'}</span><strong>${escapeHtml(e.name)}</strong><small>${escapeHtml(e.ip||(dep?dep.name:'Sem configuração'))}</small>`;el.addEventListener('pointerdown',dragStart);el.addEventListener('dblclick',ev=>{ev.stopPropagation();openModal(e.id)});el.addEventListener('click',ev=>{if(connectMode){ev.stopPropagation();selectConnect(e.id)}});canvas.appendChild(el)});setTimeout(drawConnections,0)}
function dragStart(ev){if(connectMode)return;const el=ev.currentTarget,e=project.equipment.find(x=>x.id===el.dataset.id);if(!e)return;ev.preventDefault();el.setPointerCapture(ev.pointerId);const cr=$('#networkCanvas').getBoundingClientRect(),er=el.getBoundingClientRect(),ox=ev.clientX-er.left,oy=ev.clientY-er.top;function move(m){let x=m.clientX-cr.left-ox,y=m.clientY-cr.top-oy;x=Math.max(0,Math.min(x,cr.width-el.offsetWidth));y=Math.max(0,Math.min(y,cr.height-el.offsetHeight));e.x=Math.round(x);e.y=Math.round(y);el.style.left=e.x+'px';el.style.top=e.y+'px';drawConnections()}function up(){el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)}el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)}
function startConnect(){if(project.equipment.length<2)return alert('Adicione pelo menos dois equipamentos.');connectMode=true;firstConnect=null;$('#btnConectar').classList.add('hidden');$('#btnCancelarConexao').classList.remove('hidden');$('#statusConexao').textContent='Modo conectar: clique no primeiro equipamento.';$('#statusConexao').classList.add('active')}
function cancelConnect(){connectMode=false;firstConnect=null;$('#btnConectar').classList.remove('hidden');$('#btnCancelarConexao').classList.add('hidden');$('#statusConexao').textContent='Arraste os equipamentos para organizar a rede. Dê dois cliques para editar.';$('#statusConexao').classList.remove('active');$$('.equipment').forEach(el=>el.classList.remove('selected'))}
function selectConnect(eqId){if(!firstConnect){firstConnect=eqId;document.querySelector(`.equipment[data-id="${eqId}"]`)?.classList.add('selected');$('#statusConexao').textContent='Agora clique no segundo equipamento.';return}if(firstConnect===eqId)return alert('Escolha outro equipamento.');const exists=project.connections.some(c=>(c.from===firstConnect&&c.to===eqId)||(c.from===eqId&&c.to===firstConnect));if(exists){alert('Esses equipamentos já estão conectados.');return cancelConnect()}const a=project.equipment.find(e=>e.id===firstConnect),b=project.equipment.find(e=>e.id===eqId);project.connections.push({id:id('con'),from:firstConnect,to:eqId});addHistory('Configuração',`Conexão criada entre ${a.name} e ${b.name}.`);cancelConnect();renderAll()}
function drawConnections(){const svg=$('#connectionLayer'),canvas=$('#networkCanvas');if(!svg||!canvas)return;svg.setAttribute('viewBox',`0 0 ${canvas.clientWidth} ${canvas.clientHeight}`);svg.innerHTML='';project.connections.forEach(c=>{const a=document.querySelector(`.equipment[data-id="${c.from}"]`),b=document.querySelector(`.equipment[data-id="${c.to}"]`);if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.offsetLeft+a.offsetWidth/2);line.setAttribute('y1',a.offsetTop+a.offsetHeight/2);line.setAttribute('x2',b.offsetLeft+b.offsetWidth/2);line.setAttribute('y2',b.offsetTop+b.offsetHeight/2);line.setAttribute('stroke','#2563eb');line.setAttribute('stroke-width','4');line.setAttribute('stroke-linecap','round');line.setAttribute('opacity','.75');svg.appendChild(line)})}
function fillDepartmentSelect(){const s=$('#equipDepartamento');s.innerHTML='<option value="">Sem departamento</option>';project.departments.forEach(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=d.name;s.appendChild(o)})}
function openModal(eqId){const e=project.equipment.find(x=>x.id===eqId);if(!e)return;editingId=eqId;fillDepartmentSelect();$('#equipNome').value=e.name;$('#equipDepartamento').value=e.departmentId||'';$('#equipIp').value=e.ip;$('#equipPrefixo').value=e.prefix;$('#equipMac').value=e.mac;$('#equipStatus').value=e.status;$('#equipObservacoes').value=e.notes;$('#modalEquipamento').classList.remove('hidden')}
function closeModal(){editingId=null;$('#modalEquipamento').classList.add('hidden')}
function saveEquipmentEdit(){const e=project.equipment.find(x=>x.id===editingId);if(!e)return;e.name=$('#equipNome').value.trim()||e.name;e.departmentId=$('#equipDepartamento').value;e.ip=$('#equipIp').value.trim();e.prefix=$('#equipPrefixo').value.trim();e.mac=$('#equipMac').value.trim();e.status=$('#equipStatus').value;e.notes=$('#equipObservacoes').value.trim();addHistory('Configuração',`${e.name} teve suas configurações atualizadas.`);closeModal();renderAll()}
function deleteCurrentEquipment(){const e=project.equipment.find(x=>x.id===editingId);if(!e)return;if(!confirm(`Excluir ${e.name}?`))return;project.equipment=project.equipment.filter(x=>x.id!==e.id);project.connections=project.connections.filter(c=>c.from!==e.id&&c.to!==e.id);addHistory('Correção',`${e.name} foi removido da rede.`);closeModal();renderAll()}

function setupHistory(){ $('#btnAdicionarHistorico').addEventListener('click',()=>{const description=$('#historicoDescricao').value.trim();if(!description)return alert('Descreva o que foi feito.');project.history.unshift({id:id('hist'),date:$('#historicoData').value||today(),type:$('#historicoTipo').value,description});$('#historicoDescricao').value='';$('#historicoData').value=today();renderAll()}) }
function setupSaveOpen(){ $('#btnSalvarProjeto').addEventListener('click',saveProject);$('#inputAbrirProjeto').addEventListener('change',ev=>{const file=ev.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.company||!Array.isArray(d.equipment))throw new Error();project={version:d.version||1,company:d.company||emptyProject().company,departments:Array.isArray(d.departments)?d.departments:[],equipment:Array.isArray(d.equipment)?d.equipment:[],connections:Array.isArray(d.connections)?d.connections:[],history:Array.isArray(d.history)?d.history:[]};cancelConnect();renderAll();alert('Projeto carregado com sucesso.')}catch{alert('Arquivo inválido. Selecione o JSON salvo por este projeto.')}finally{ev.target.value=''}};r.readAsText(file,'UTF-8')}) }
function saveProject(){const safe=(project.company.name||'Minha_Empresa').trim().replace(/\s+/g,'_').replace(/[^\wÀ-ÿ-]/g,'');const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Rede_${safe}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

function renderDashboard(){$('#statEquipamentos').textContent=project.equipment.length;$('#statDepartamentos').textContent=project.departments.length;$('#statConexoes').textContent=project.connections.length;$('#statHistorico').textContent=project.history.length;$('#tituloEmpresa').textContent=project.company.name||'Minha Empresa';let t=`${project.company.name||'Minha Empresa'} possui ${project.equipment.length} equipamento(s), ${project.departments.length} departamento(s) e ${project.connections.length} conexão(ões).`;if(project.company.description)t+=' '+project.company.description;$('#resumoEmpresa').textContent=t}
function renderCompany(){$('#empresaNome').value=project.company.name||'';$('#empresaGrupo').value=project.company.group||'';$('#empresaIntegrantes').value=project.company.members||'';$('#empresaDescricao').value=project.company.description||''}
function renderDepartments(){const list=$('#listaDepartamentos');list.innerHTML='';if(!project.departments.length){list.innerHTML='<div class="panel"><p>Nenhum departamento criado ainda.</p></div>';return}project.departments.forEach(d=>{const count=project.equipment.filter(e=>e.departmentId===d.id).length,card=document.createElement('article');card.className='department-card';card.innerHTML=`<h3>${escapeHtml(d.name)}</h3><p>${count} equipamento(s)</p><button class="btn btn-danger">Excluir</button>`;card.querySelector('button').addEventListener('click',()=>deleteDepartment(d.id));list.appendChild(card)})}
function renderAddressTable(){const b=$('#tabelaEnderecos');b.innerHTML='';if(!project.equipment.length){b.innerHTML='<tr><td colspan="7">Nenhum equipamento cadastrado.</td></tr>';return}project.equipment.forEach(e=>{const dep=project.departments.find(d=>d.id===e.departmentId),tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(e.name)}</td><td>${escapeHtml(typeNames[e.type]||e.type)}</td><td>${escapeHtml(dep?dep.name:'-')}</td><td>${escapeHtml(e.ip||'-')}</td><td>${escapeHtml(e.prefix||'-')}</td><td>${escapeHtml(e.mac||'-')}</td><td><span class="status ${e.status}">${statusText(e.status)}</span></td>`;b.appendChild(tr)})}
function renderHistory(){const list=$('#listaHistorico');list.innerHTML='';if(!project.history.length){list.innerHTML='<div class="panel"><p>Nenhuma alteração registrada ainda.</p></div>';return}project.history.forEach(h=>{const [y,m,d]=(h.date||today()).split('-'),el=document.createElement('article');el.className='timeline-item';el.innerHTML=`<div class="timeline-meta">${d}/${m}/${y} • ${escapeHtml(h.type)}</div><p>${escapeHtml(h.description)}</p>`;list.appendChild(el)})}
function renderAll(){renderDashboard();renderCompany();renderDepartments();renderMap();renderAddressTable();renderHistory()}
